# version: '3.1'

# services:
#   app:
#     build: .
#     image: afmpro-admin-image
#     container_name: afmpro-admin-front
#     restart: always
#     networks:
#       - proxynet

# networks:
#   proxynet:
#     external: true

services:
  afmpro-admin:
    image: $IMAGE_NAME:$IMAGE_TAG
    container_name: afmpro-admin
    restart: always
    networks:
      proxynet:

networks:
  proxynet:
    external: true
    name: proxynet
