version: '3.1'

services:
  app:
    build: .
    image: acp-admin-image
    container_name: acp-admin-front
    restart: always
    ports:
      - "3007:80"
    networks:
      - proxynet

networks:
  proxynet:
    external: true
